name: Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: localnet.Dockerfile
          network: host
          no-cache: true
          tags: onomy/aurora-engine-local:latest,onomy/aurora-engine-local:v-${{ steps.buildnumber.outputs.build_number }}
