---
on:
  schedule:
    - cron: '27 8 * * 1,4'
name: Scheduled_Lints
jobs:
  clippy:
    name: Nightly_Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make etc/eth-contracts/res/EvmErc20.bin
      - name: Update toolchain
        run: rustup update nightly
      - name: Run cargo clippy
        run: cargo +nightly clippy --no-default-features --features=mainnet -- -D warnings
